name: Verify
run-name: Verify ${{ github.ref }}
on:
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm i
      - run: pnpm build:libs
      - run: pnpm build
      - run: pnpm exec playwright install --with-deps
      - run: echo -e "GH_APP_ID=a\nGH_CLIENT_ID=b\nGH_CLIENT_SECRET=c\n" > .env.local
      - run: pnpm test
      - run: pnpm fmtcheck
      - run: echo 'Look what hell made'
